package com.tawajood.snail.utils

object Constants {
    const val LANG = "lang"
    const val EN = "en"
    const val AR = "ar"
    const val IS_ON="1"
    const val IS_FIRST = "is_first"
    const val TOKEN = "token"
    const val FCM_TOKEN = "fcm_token"
    const val USER_ID = "user_id"
    const val USERNAME = "username"
    const val PHONE = "phone"
    const val COUNTRY_CODE = "country_code"
    const val USER_IMAGE = "user_image"
    const val IS_NOTIFIABLE = "user_image"
    const val EMAIL = "email"
    const val LAT = "lat"
    const val LNG = "lng"
    const val PARKING = "parking"
    const val SMS_TOKEN = "Bearer av9ZwgJyL-6SqEcFCWlS52gOEUgQ_50EcgtNMrfbaeY"
    const val _DATA = "_data"
    const val REG_BODY = "reg_body"
    const val VER_CODE = "ver_code"
    const val MSG = "msg"
    const val IMAGE = "image"
    const val CLINIC = "clinic"
    const val CLINIC_NAME = "name"
    const val REVIEW_CLINIC = "review"
    const val PET_ID = "id"
    const val REQUEST_ID = "id"
    const val CAT_ID = "id"
    const val VENDOR_ID = "id"
    const val SUB_CAT_ID = "id"
    const val PRODUCT_ID = "id"
    const val CART_COUNT = "c"
    const val OPEN_NOTIFICATION = "open_not"
    const val RECEIVER_ID = "receiver_id"
    const val ORDER_ID = "o"


    const val TEST_TOKEN = "EQGCV7fyuVwcBLRfgxOtKMl_8IOgsLVvhD__WiPaOn9leBYXFXew2nch9gDxvjApLeiKAhaj2mkkcM3Cm2fsdnFDr-FGG_U5oplEpcdn1uea8gh7j8PVlepxL5EDAYzNusRAeizrIGi0-X5SIOxNzADpj6Degg7S07Bhi1f6zSXwLJyr340hfhN4CuKSb3-NpY8_DBTMJquWpyyuha7O58SZN441kjNZxZXTehkW2CfeVpIBPjbkcUFhAEIVBooJjAppJCAyrkez5fOaCLmABeHfnKVMmnRLTosI_oOLcp1ssSg_JRwfdEkcahiC24Dyl2iOjC_7Tij_uGxIvKT8sR1zINloJcNvgvs8ELgDxdwQbN2SGv4iKhIMzt5Rj9iqaqcnV0n3b8rmD-3WiQCTHAvcxG4CCIXXwZyCvLI6Jkcq0MOwEQf7_weCLhA_M1ZTg01l3byBEc059s3Gtu2Wz42GuhAI23ZX1nl1OlFEb4fD029q4fVDHGsSMFQQGtmtcx4_VLGAYb3EXbRQYUOyuHW3DkDpx0AYT0H7en4SEiB_fSlp3ZXH5WarkoXnGTUJ_1IHsPqtHUZeby2tCgb5-5ycZY34bkiaTu_2IcnKXdaCTubb7Rj4sy-atslcvH_kTZq9TRhlkSDsK-vtoCMqvAfmtGUFk0qxM0p9nZnYvZ6s2UXL-t5XZM7V6fCW7oP-uXGX-sMOajeX65JOf6XVpk29DP6ro8WTAflCDANC193yof8-f5_EYY-3hXhJj7RBXmizDpneEQDSaSz5sFk0sV5qPcARJ9zGG73vuGFyenjPPmtDtXtpx35A-BVcOSBYVIWe9kndG3nclfefjKEuZ3m4jL9Gg1h2JBvmXSMYiZtp9MR5I6pvbvylU_PP5xJFSjVTIz7IQSjcVGO41npnwIxRXNRxFOdIUHn0tjQ-7LwvEcTXyPsHXcMD8WtgBh-wxR8aKX7WPSsT1O8d8reb2aR7K3rkV3K82K_0OgawImEpwSvp9MNKynEAJQS6ZHe_J_l77652xwPNxMRTMASk1ZsJL"
    const val TEST_API_URL = "https://apitest.myfatoorah.com/"

}